### ISSUE TITLE
Custom Screen Mini Portraits (Resolved, See 2nd Post)

### ISSUE THREAD

**Issue by FinalInsanity** [Tildehat/EOU-Classic-Mod#1]
The Landsknecht's mini portraits in the "custom" menu instead displays the corresponding Gunner portrait. Highlander/Gunner custom minis are also a little messed up as far as display goes, particularly Gunner 4, though all of them lack the curve on the left side.

I realize it's been a couple years since this was last updated, but figured I'd put it out there just in case.

**Comment by FinalInsanity** [comment]
I did some investigating and figured out the cause. First, the code.ips included in the current release isn't up to date with the current patch.s file, which is what caused the issue with Landsknecht. Updating the code.ips fixed this issue.

For Highlander and Gunner it was simply a matter of changing the image format, and re-importing with the fixes. Well, Gunner 4 was a little more complicated due to some strange resizing issue, but yeah. Should anyone stumble upon this and this never gets updated by Tildehat themselves, _I've gone ahead and created a fork with an updated release_. If an updated/fixed version already existed... well, I'd sure feel like a fool, but I was unable to find it in any of my searches.

Tildehat, if you should see this, thank you so very much for your work to create this mod and bring EOU's Classic up to par with EO2U's.

**Comment by Tildehat** [comment]
Hey thanks for brining this to my attention. Sorry I took so long to respond to it but good on you for resolving it on your own. I've pushed out a fix on my end(along with a couple other things I saw needed to be fixed).
